server:
  port: 8082
spring:
  application:
    name: m-login  
  sleuth: 
    sampler:
      percentage: 100.0 
  rabbitmq:
    host: 172.16.3.131
    port: 5672
    username: rabbit
    password: passwd 
    
  redis:
      # Redis服务器地址
      host: 172.16.3.131
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例
        max-idle: 100
        # 控制一个pool最少有多少个状态为idle(空闲的)的jedis实例
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 表示当borrow(引入)一个jedis实例时，最大的等待时间，如果超过等待时间(毫秒)，则直接抛出JedisConnectionException；
        max-wait: 1000
      # 连接超时时间（毫秒）
      timeout: 2000
feign: 
  hystrix:  
    enabled: true  
hystrix: 
  shareSecurityContext: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password111@172.16.3.131:8761/eureka/
#        defaultZone: http://user:password111@localhost:8761/eureka/
  instance:
#    ip-address: 172.16.3.131
    prefer-ip-address: true
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    statusPageUrl: http://${eureka.hostname}/info
#    healthCheckUrl: http://${eureka.hostname}/health
#    homePageUrl: http://${eureka.hostname}/
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

logging:
  config: classpath:logback-spring.xml

redisson:
  address: 172.16.3.131:6379
  password: 
  
#哨兵模式 
#redisson:
#  master-name: mymaster
#  password: 
#  sentinel-addresses: 10.47.91.83:26379,10.47.91.83:26380,10.47.91.83:26381
  

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45
  
client:
  id: ace-auth
  secret: 123456
  token-header: x-client-token
  expire: 14400
  rsa-secret: x2318^^(*WRYQWR(QW&T
  
token:
  internal:
    name: accessToken
    refresh: 30 # min
  login:
    name: login

request:
  ignore:
    startWith: /login,/logout
  
