#server
server:   
  port: 8083
feign: 
  hystrix:  
    enabled: true 
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:password111@172.16.2.131:8761/eureka/
  instance:
#    ip-address: 172.16.3.131
    prefer-ip-address: true

#datasource
spring:
    application:
      name: m-provider-elevator
#    cloud:
#     inetutils:
#        use-only-site-local-interfaces: true
    zipkin:
      base-url: http://172.16.2.131:9411   
    sleuth: 
      sampler:
        probability: 1
        
#    rabbitmq:
#      host: 172.16.3.131
#      port: 5672
#      username: rabbit
#      password: passwd
    datasource:
        name: mic_db
        url: jdbc:mysql://172.16.2.131:3306/mic_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: radlly
        password: radlly.XU82!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 3000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        spring.datasource.filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true
        debug: true    
#debug: true
# mybatis_config
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
logging:
    config: classpath:logback-spring.xml

request:
  ignore: 
    startWith:  #split with ","
    
baidu:
    keys: 
      - f247cdb592eb43ebac6ccd27f796e2d2
      - 4rcKAZKG9OIl0wDkICSLx8BA
      - yQBIj4sdILLqW5iLZEvNdPMUseFB3ozG
      - 7d9fbeb43e975cd1e9477a7e5d5e192a
      - 42b8ececa9cd6fe72ae4cddd77c0da5d
      - DE1B2vE0ZkeiPV49jyjDAc0PNNRBUa0E